version: '3.5'

services:
  postgres:
    image: postgres:9.6.23-stretch
    restart: always
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_secret
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    secrets:
      - postgres_secret
    networks:
      - manymanager_net

  manymanager:
    image: manymanager
    build: .
    restart: always
    env_file:
      - ./environment.env
     # - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - postgres
    networks:
      - manymanager_net

  nginx:
    image: nginx:1.21.0
    restart: always
    ports:
      - "2048:2048"
    volumes:
      - ./dashboard/static:/manymanager/dashboard/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - manymanager
    networks:
      - manymanager_net

secrets:
  postgres_secret:
    file: postgres_pw.txt

networks:
  manymanager_net:
    driver: bridge

volumes:
  postgres_volume:
  manymanager_static:

configs:
  nginx_conf:
    file: nginx.conf
