"""empty message

Revision ID: 036a4415d72c
Revises: af31ec24dfd8
Create Date: 2022-08-19 00:01:32.409743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036a4415d72c'
down_revision = 'af31ec24dfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'active')
    # ### end Alembic commands ###
