"""empty message

Revision ID: 2b564a533428
Revises: 
Create Date: 2022-08-18 15:57:35.964180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b564a533428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('share', 'expiration_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('expiration_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('share', 'active')
    # ### end Alembic commands ###
