"""empty message

Revision ID: a2a4de209eda
Revises: c183813127c0
Create Date: 2022-08-19 11:45:38.339437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a4de209eda'
down_revision = 'c183813127c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('shared_user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('share_shared_with_fkey', 'share', type_='foreignkey')
    op.create_foreign_key(None, 'share', 'user', ['shared_user_id'], ['id'])
    op.drop_column('share', 'shared_with')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('shared_with', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'share', type_='foreignkey')
    op.create_foreign_key('share_shared_with_fkey', 'share', 'user', ['shared_with'], ['id'])
    op.drop_column('share', 'shared_user_id')
    # ### end Alembic commands ###
