"""empty message

Revision ID: aa1af1a3d71d
Revises: f42719617e8b
Create Date: 2022-08-26 22:59:58.864997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1af1a3d71d'
down_revision = 'f42719617e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('expense_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'alert', 'expense', ['expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.drop_column('alert', 'expense_id')
    # ### end Alembic commands ###
