"""empty message

Revision ID: af31ec24dfd8
Revises: 2b564a533428
Create Date: 2022-08-18 23:33:58.374779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af31ec24dfd8'
down_revision = '2b564a533428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'accepted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
