"""empty message

Revision ID: c183813127c0
Revises: 764bd3a0a490
Create Date: 2022-08-19 11:34:45.798495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c183813127c0'
down_revision = '764bd3a0a490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('shared_with', sa.BigInteger(), nullable=False))
    op.alter_column('share', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_foreign_key(None, 'share', 'user', ['shared_with'], ['id'])
    op.drop_column('share', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'share', type_='foreignkey')
    op.alter_column('share', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('share', 'shared_with')
    # ### end Alembic commands ###
